File ini buat coba2 ya gais sebelum di-implement ke <code>main.py</code>-nya

In [2]:
import numpy as np
import math

In [3]:
def translation(point, tx, ty, tz) -> np.ndarray:
    if(len(point) < 4):
        point = np.append(point, 1)
        
    translation_matrix = np.array([[1,0,0,tx],
                                  [0,1,0,ty],
                                  [0,0,1,tz],
                                  [0,0,0,1]])
    return translation_matrix @ point 

def scaling(point, sx, sy, sz) -> np.ndarray:
    if(len(point) < 4):
        point = np.append(point, 1)

    scaling_matrix = np.array([[sx,0,0,0],
                               [0,sy,0,0],
                               [0,0,sz,0],
                               [0,0,0,1]])

    # return scaling_matrix @ point
    return (scaling_matrix @ point)[:-1] #slicing index terakhir biar hasilnya [x,y,z] instead of [x,y,z,1]

def shearxy(point, shx, shy):
    if(len(point) < 4):
        point = np.append(point, 1)

    shearxy_matrix = np.array([[1,0,shx,0],
                               [0,1,shy,0],
                               [0,0,1,0],
                               [0,0,0,1]])
    return shearxy_matrix @ point 

def shearyz(point, shy, shz):
    if(len(point) < 4):
        point = np.append(point, 1)

    shearyz_matrix = np.array([[1,0,0,0],
                               [0,shy,0,0],
                               [0,shz,1,0],
                               [0,0,0,1]])
    return shearyz_matrix @ point 

def shearxz(point, shx, shz):
    if(len(point) < 4):
        point = np.append(point, 1)

    shearxz_matrix = np.array([[shx,0,0,0],
                               [0,1,0,0],
                               [shz,0,1,0],
                               [0,0,0,1]])
    return shearxz_matrix @ point

def shear(point, sh_factor: list, sh_type):
    if(len(point) < 4):
        point = np.append(point, 1)

    if sh_type == "xy":
        return shearxy(point, sh_factor[0], sh_factor[1])
    elif sh_type == "yz":
        return shearyz(point, sh_factor[1], sh_factor[2])
    elif sh_type == "xz":
        return shearxz(point, sh_factor[0], sh_factor[2])

        

In [4]:
test = np.array([1,1,1])

##### Scale Test

In [5]:
print(scaling(test, 1, 2, 3))

[1 2 3]


##### Translate Test

In [6]:
print(translation(test, 1, 2 ,3))

[2 3 4 1]


##### Shear Test

In [7]:
print(type(test))
print(shearxy(test, 2, 2))
print(shearyz(test, 2, 2))
print(shearxz(test, 2, 2))

shear_factor = [2,2,2]
print(shear(test, shear_factor, "xy"))
print(shear(test, shear_factor, "yz"))
print(shear(test, shear_factor, "xz"))

<class 'numpy.ndarray'>
[3 3 1 1]
[1 2 3 1]
[2 1 3 1]
[3 3 1 1]
[1 2 3 1]
[2 1 3 1]


#### Rotation Matrix